version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["react"]
  environment = ["react-native"]

[[analyzers]]
name = "test-coverage"
enabled = true

test_patterns = [
  "**/__tests__/**"
]
