module.exports = {
  preset: 'jest-expo',
  setupFilesAfterEnv: ['<rootDir>/jest-setup.ts'],
  testMatch: ['**/?(*.)+(spec|test).ts?(x)'],
  collectCoverage: true,
  collectCoverageFrom: ['src/**/*.{ts,tsx}', '!**/coverage/**', '!**/node_modules/**', '!**/babel.config.js', '!**/jest.setup.js', '!**/docs/**', '!**/cli/**', '!**/ios/**', '!**/android/**'],
  moduleFileExtensions: ['js', 'ts', 'tsx'],
  moduleDirectories: ['node_modules', '<rootDir>/'],
  transformIgnorePatterns: [
    'node_modules/(?:\.pnpm|\.store)',
    'node_modules/(?!jest-react-native)',
    'node_modules/(?!react-native)',
    'node_modules/(?!@react-native)',
    'node_modules/(?!@react-native-community)',
    'node_modules/(?!expo)',
    'node_modules/(?!exponent)',
    'node_modules/(?!@expo)',
    'node_modules/(?!@exponent)',
    'node_modules/(?!@expo-google-fonts)',
    'node_modules/(?!react-navigation)',
    'node_modules/(?!@react-navigation)',
    'node_modules/(?!@unimodules)',
    'node_modules/(?!unimodules)',
    'node_modules/(?!@sentry)',
    'node_modules/(?!native-base)',
    'node_modules/(?!react-native-svg)',
    'node_modules/(?!lucide-react-native)',
    'node_modules/(?!@tanstack)',
    'node_modules/(?!moti)',
    'node_modules/(?!nativewind)',
    'node_modules/(?!tailwind-variants)',
    'node_modules/(?!@react-native-aria)',
    'node_modules/(?!@gluestack-ui)',
  ],
  coverageReporters: ['json-summary', ['text', { file: 'coverage.txt' }]],
  reporters: [
    'default',
    ['github-actions', { silent: false }],
    'summary',
    [
      'jest-junit',
      {
        outputDirectory: 'coverage',
        outputName: 'jest-junit.xml',
        ancestorSeparator: ' › ',
        uniqueOutputName: 'false',
        suiteNameTemplate: '{filepath}',
        classNameTemplate: '{classname}',
        titleTemplate: '{title}',
      },
    ],
  ],
  coverageDirectory: '<rootDir>/coverage/',
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
  },
};
