#!/bin/sh
set -e

# Directory where the built web app is served
HTML_DIR="/usr/share/nginx/html"

# Create the env-config.js file with environment variables
cat > "${HTML_DIR}/env-config.js" << EOF
// Runtime environment configuration - generated by docker-entrypoint.sh
// This file is generated at container startup and injects environment variables
window.__ENV__ = {
  APP_ENV: "${APP_ENV:-production}",
  NAME: "${UNIT_NAME:-Resgrid Unit}",
  SCHEME: "${UNIT_SCHEME:-ResgridUnit}",
  VERSION: "${UNIT_VERSION:-0.0.1}",
  BASE_API_URL: "${UNIT_BASE_API_URL:-https://api.resgrid.com}",
  API_VERSION: "${UNIT_API_VERSION:-v4}",
  RESGRID_API_URL: "${UNIT_RESGRID_API_URL:-/api/v4}",
  CHANNEL_HUB_NAME: "${UNIT_CHANNEL_HUB_NAME:-eventingHub}",
  REALTIME_GEO_HUB_NAME: "${UNIT_REALTIME_GEO_HUB_NAME:-geolocationHub}",
  LOGGING_KEY: "${UNIT_LOGGING_KEY:-}",
  APP_KEY: "${UNIT_APP_KEY:-}",
  UNIT_MAPBOX_PUBKEY: "${UNIT_MAPBOX_PUBKEY:-}",
  IS_MOBILE_APP: false,
  SENTRY_DSN: "${UNIT_SENTRY_DSN:-}",
  COUNTLY_APP_KEY: "${UNIT_COUNTLY_APP_KEY:-}",
  COUNTLY_SERVER_URL: "${UNIT_COUNTLY_SERVER_URL:-}"
};
EOF

echo "Generated env-config.js with runtime environment variables"

# Check if index.html exists
if [ ! -f "${HTML_DIR}/index.html" ]; then
  echo "Error: index.html not found in ${HTML_DIR}"
  exit 1
fi

# Inject the env-config.js script into index.html if not already present
if ! grep -q "env-config.js" "${HTML_DIR}/index.html"; then
  # Insert script tag right after the opening <head> tag
  sed -i 's|<head>|<head>\n    <script src="/env-config.js"></script>|' "${HTML_DIR}/index.html"
  echo "Injected env-config.js script tag into index.html"
else
  echo "env-config.js already present in index.html"
fi

echo "Starting nginx..."

# Execute the CMD (nginx)
exec "$@"
