# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.199.0"
fastlane_require 'xcodeproj'

default_platform :ios

platform :ios do
	lane :certificates do
    setup_ci
    
    app_store_connect_api_key(
			key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
			issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
			key_content: ENV["APPLE_APIKEY"],
			is_key_content_base64: true,
			duration: 120,
			in_house: false
		)

    match(git_url: ENV["MATCH_GIT_URL"], git_basic_authorization: ENV["MATCH_GIT_BASIC_AUTHORIZATION"], type: "development", app_identifier: ENV["MATCH_UNIT_BUNDLEID"], readonly: true)
		match(git_url: ENV["MATCH_GIT_URL"], git_basic_authorization: ENV["MATCH_GIT_BASIC_AUTHORIZATION"], type: "adhoc", app_identifier: ENV["MATCH_UNIT_BUNDLEID"], readonly: true)
    match(git_url: ENV["MATCH_GIT_URL"], git_basic_authorization: ENV["MATCH_GIT_BASIC_AUTHORIZATION"], type: "appstore", app_identifier: ENV["MATCH_UNIT_BUNDLEID"], readonly: true)
	end
end
