/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/calls` | `/calls`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/contacts` | `/contacts`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/notes` | `/notes`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/protocols` | `/protocols`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/feed/add-post`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/login/login-form`; params?: Router.UnknownInputParams; } | { pathname: `/[...messing]`, params: Router.UnknownInputParams & { messing: (string | number)[]; } } | { pathname: `/call/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/feed/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/onboarding`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/calls` | `/calls`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/contacts` | `/contacts`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/notes` | `/notes`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/protocols` | `/protocols`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/feed/add-post`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/login/login-form`; params?: Router.UnknownOutputParams; } | { pathname: `/[...messing]`, params: Router.UnknownOutputParams & { messing: string[]; } } | { pathname: `/call/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/feed/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/onboarding${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/calls${`?${string}` | `#${string}` | ''}` | `/calls${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/contacts${`?${string}` | `#${string}` | ''}` | `/contacts${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/notes${`?${string}` | `#${string}` | ''}` | `/notes${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/protocols${`?${string}` | `#${string}` | ''}` | `/protocols${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/feed/add-post${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/login/login-form${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/calls` | `/calls`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/contacts` | `/contacts`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/notes` | `/notes`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/protocols` | `/protocols`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/feed/add-post`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/login/login-form`; params?: Router.UnknownInputParams; } | `/${string}` | `/call/${Router.SingleRoutePart<T>}` | `/feed/${Router.SingleRoutePart<T>}` | { pathname: `/[...messing]`, params: Router.UnknownInputParams & { messing: (string | number)[]; } } | { pathname: `/call/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/feed/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
